
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: nandy@04
  database: dribble_db

development:
  <<: *default
  database: "dribble_db"

test:
  <<: *default
  database: "dribble_db"